### ISSUE TITLE
Integrating SUQS, world state queries?

### ISSUE THREAD

**Issue by Olaxan** [sinbad/SUDS#1]
Hi, Steve!

This looks like yet another amazing plugin, and could help our project a huge lot. 
I would much prefer to write my dialogue outside of Unreal, so this looks like the best of two worlds.

I was wondering how one would go about attempting to query an external system, such as SUQS, in the dialogue -- either for options or NPC replies. From what I gathered, branching mainly happens with the use of expressions and variables.

What would be very nice is being able to put something like `[if {IsQuestCompleted(q_putTrollInBag)}]` directly in the script. Then the burden of testing the world state can be placed upon SUQS, and the script remains simple (supplying only a name).

The dialogue plugin we're currently using allows you to define custom scriptable conditions for such an occasion, which is a helpful feature (a class with a single virtual function `IsConditionSatisfied -> bool`), but I understand that may be tricky to consolidate with the relatively simple script files of SUDS.

Is such a system something you'd consider, or perhaps already supported somehow?
Thanks in advance!

**Comment by sinbad** [comment]
To avoid over-complicating integration, everything is done via variables. Participants are the best integration point here, and either you can set variables ahead of time using during OnDialogueStarting, or on demand as they are requested in the dialogue using OnDialogueVariableRequested. I use a mixture of both in my dialogues.

So rather than considering it from a perspective of needing to have SUDS be able to query other plugins, consider that anything can be registered as a ISUDSParticipant and therefore provide variables on demand or on dialogue start, such as a SUQS/SUDS bridge object. All you have to do is set a naming convention for those variables.

Cheers
Steve

**Comment by sinbad** [comment]
Side note: variable names can have dots in them which helps with naming. So you could have {Quests.Q_DoTheThing.IsComplete} for example.

**Comment by Olaxan** [comment]
Right! That makes sense. Adding a separate bridge object is a good idea; I was hesitant of going via the participant at first because I was afraid I'd have to duplicate the logic for every speaking object in the game, but that resolves that neatly.

Thank you! I have another point of feedback/suggestion, but I'll open a new issue for that. I'm really hoping we can integrate this plugin into our project -- I'm not overly fond of stringing together dialogue tree graphs manually the way we do now, it makes writing a little bit of a chore. This is much more comprehensive.
