### ISSUE TITLE
Can't Generate StringTable when import sud file, in UE5.3.2

### ISSUE THREAD

**Issue by thorcx** [sinbad/SUDS#20]
Hi, i'm try to use this plugin, but when i write a .sud script, and import in in Unreal Editor, there's only a SUDSScript asset file generated, there is no String Table. I don't know how to correctly generate String table, is it a bug?

**Comment by sinbad** [comment]
There is actually a string table there, you just can't see it anymore. UE stopped displaying secondary assets contained in a single .uasset in the content browser but it's still there. It's actually quite nice now since it's less distracting, and the localisation dashboard can still see the string table so everything works fine.
