### ISSUE TITLE
Incrementing TextIds create fragile localization scenarios.

### ISSUE THREAD

**Issue by edwinwalda** [sinbad/SUDS#4]
You've already mentioned in the documentation that the incrementing text ids can cause problems if scripts are getting edited during a localization process. My naive thought would be this could be resolved by using GUIDs instead of incrementing numbers for the text ids. Are there any reasons this can't be done, given the current state of the library?

**Comment by sinbad** [comment]
It doesn't matter how the numbers are generated. What matters is that they have to be linked to the line in the source text in order to stay consistent with any parallel localisation efforts. Whether you use GUIDs or incrementing numbers that problem remains the same. I picked incrementing numbers scoped to each script because they're shorter and therefore as obtrusive as possible, but still it's not nice to have them cluttering up your source if you don't need it. Realistically you don't want to be starting to localise until the text is reasonably static anyway, which is why we don't enforce their write back to the source until you're ready.

**Comment by edwinwalda** [comment]
Thanks for the quick response! I think I miss understood something reading the documentation.
